'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Christmas_Clock.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property c_mas_tree_with_clock() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("c_mas_tree_with_clock", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Carol_of_the_Bells() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Carol_of_the_Bells", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property cmas_tree_with_clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmas_tree_with_clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dance_Of_The_Sugar_Plum_Fairies__Short_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Dance_Of_The_Sugar_Plum_Fairies__Short_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -1
        '''-16777216
        '''True
        '''True
        '''.
        '''</summary>
        Friend ReadOnly Property InitInfo() As String
            Get
                Return ResourceManager.GetString("InitInfo", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Jingle_Bells() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Jingle_Bells", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Joy_to_the_World() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Joy_to_the_World", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property O_Christmas_Tree() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("O_Christmas_Tree", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Silent_Night() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Night", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property swap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property test() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("test", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property The_First_Noel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("The_First_Noel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property to_corner_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("to_corner_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property to_corner_small_transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("to_corner_small_transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property What_Child_is_This() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Child_is_This", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
