'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Christmas_Clock.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property A_Blessed_Winter_Home() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("A_Blessed_Winter_Home", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Adeste_Fideles() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Adeste_Fideles", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Angels_Medley() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Angels_Medley", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Angels_We_Have_Heard_On_High() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Angels_We_Have_Heard_On_High", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Angels_We_Have_Heard_on_High__2_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Angels_We_Have_Heard_on_High__2_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Away_in_a_Manger() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Away_in_a_Manger", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property c_mas_tree_with_clock() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("c_mas_tree_with_clock", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property c_mas_tree_with_clock1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("c_mas_tree_with_clock1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property c_mas_tree_with_clock2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c_mas_tree_with_clock2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Celebration_of_Life() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Celebration_of_Life", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property cmas_tree_with_clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmas_tree_with_clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Come_Thou_Long_Expected_Jesus() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Come_Thou_Long_Expected_Jesus", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Coventry_Carol() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Coventry_Carol", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Dance_of_the_Reed_Flutes() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Dance_of_the_Reed_Flutes", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Dance_Of_The_Sugar_Plum_Fairies__Short_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Dance_Of_The_Sugar_Plum_Fairies__Short_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Dance_Of_The_Sugar_Plum_Fairies__Short_1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Dance_Of_The_Sugar_Plum_Fairies__Short_1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Deck_the_Halls() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Deck_the_Halls", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Drive_the_Cold_Winter_Away() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Drive_the_Cold_Winter_Away", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Entre_le_boeuf() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Entre_le_boeuf", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property From_Heaven_Above_to_Earth_I_Come() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("From_Heaven_Above_to_Earth_I_Come", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Frost() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Frost", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Gabriel_from_Heven_King() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Gabriel_from_Heven_King", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Gifts_for_the_Country_King() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Gifts_for_the_Country_King", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property God_Rest_Ye_Merry_Gentlemen() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("God_Rest_Ye_Merry_Gentlemen", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Huron_Carol() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Huron_Carol", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property I_Wish_I_Could_Be_There_for_Christmas() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("I_Wish_I_Could_Be_There_for_Christmas", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property I_Wonder_as_I_Wander() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("I_Wonder_as_I_Wander", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -1
        '''-16777216
        '''True
        '''True
        '''True
        '''1109
        '''629
        '''.
        '''</summary>
        Friend ReadOnly Property InitInfo() As String
            Get
                Return ResourceManager.GetString("InitInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -1
        '''-16777216
        '''True
        '''True
        '''True
        '''1109
        '''629
        '''.
        '''</summary>
        Friend ReadOnly Property InitInfo1() As String
            Get
                Return ResourceManager.GetString("InitInfo1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property O_Come_Emmanuel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("O_Come_Emmanuel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property O_Little_Town_of_Bethlehem() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("O_Little_Town_of_Bethlehem", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property O_Man__Such_A_Sight_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("O_Man__Such_A_Sight_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property O_Tannenbaum() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("O_Tannenbaum", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Puer_Natus_in_Bethlehem() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Puer_Natus_in_Bethlehem", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Silent_Night() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Night", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Silent_Night1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Night1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property swap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swap1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swap1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sweeter_the_Bells_Never_Sound() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Sweeter_the_Bells_Never_Sound", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property test() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("test", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property The_First_Noel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("The_First_Noel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property The_First_Noel1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("The_First_Noel1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property The_First_Noell() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("The_First_Noell", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property The_First_Snow_of_Winter() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("The_First_Snow_of_Winter", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property The_Holly_and_The_Ivy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("The_Holly_and_The_Ivy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property The_Wintry_Mind() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("The_Wintry_Mind", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property to_corner_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("to_corner_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property to_corner_small_transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("to_corner_small_transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property to_corner_small1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("to_corner_small1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property to_corner_small2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("to_corner_small2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property We_Three_Kings() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("We_Three_Kings", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property We_Wish_You_a_Merry_Christmas() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("We_Wish_You_a_Merry_Christmas", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property What_Child_is_This() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Child_is_This", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property What_Child_is_This1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Child_is_This1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Winter_Breeze() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Winter_Breeze", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
